apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: e2e-tests
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-tests
    app.kubernetes.io/part-of: disallowed-packages
  name: e2e-tests
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: e2e-tests
status:
  loadBalancer: {}
