apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: e2e-tests-d53m
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-tests-d53m
    app.kubernetes.io/part-of: disallowed-packages
  name: e2e-tests-d53m
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: e2e-tests-d53m
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: e2e-tests-d53m
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/qe-chuo-tenant/disallowed-packages/e2e-tests-d53m@sha256:06c53abc632ce2f545f0f5f5a418115762e1db9dcccf1c2de0d8ac8bd83bff0d
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
